[package]
name = "fast_ase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
rayon = "1.10.0"
rust-htslib = "0.47.0"
twox-hash = "1.6.3"
