name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-16.04
            artifact_name: target/release/fast_ase
            asset_name: fast_ase-linux
          - name: macos
            os: macos-11
            artifact_name: target/release/fast_ase
            asset_name: fast_ase-macos

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build the binary
      run: cargo build --release

    - name: Upload the binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}